### ISSUE TITLE
Error in Using wxt dataset

### ISSUE THREAD

**Issue by mlcodeboy** [rootlu/SIAN#1]
2020.07.19-15:25:05
Namespace(batch_size=1024, biz_profile='biz_profile.npy', dataset_name='wxt', emb_size=64, epochs=100, eval_num=100, inf_flag=True, item_num=7900, item_profile='item_profile.npy', lr=0.0001, on_YARD=False, profile_size=150, save_model=True, seed=72, test_batch_size=1024, top_k=10, use_cuda=False, user_num=8163, user_profile='user_profile.npy', weight_decay=0.0005, worker_num=0)
Using cuda...
Loading data...
--- # interaction links: 2465675, social links: 8639884.0, #u_bizs: 71983, i_bizs:22218
--- #train size:1725973 #user:25049, #item:22218
--- #valid size:246568 #user:13424, #item:8075
--- #test size:493134 #user:16659, #item:11511
Load data finished 19.68671464920044s
Initializing model...
Traceback (most recent call last):
  File "./SIAN/code/trainHeteInf.py", line 486, in <module>
    main(args)
  File "./SIAN/code/trainHeteInf.py", line 271, in main
    item_num=args.item_num, biz_num=args.biz_num,
AttributeError: 'Namespace' object has no attribute 'biz_num'

May I know what the correct value of biz_num is?

**Comment by rootlu** [comment]
Hi,

the number of biz is 218,887, which has beed reported in the paper. Please refer to the paper.

Thanks.
