### ISSUE TITLE
Will Douban dataset be released?

### ISSUE THREAD

**Issue by mlcodeboy** [rootlu/SIAN#2]
I have run experiments on Yelp dataset and found the result in the paper is **reproducible.** I wonder if the Douban dataset could be made public so that a more comprehensive analysis can be done on the proposed model.

**Comment by rootlu** [comment]
Hi,

Thanks for your interest in our work.

The Douban dataset is being prepared for release, and I will release it as soon as possible.

**Comment by mlcodeboy** [comment]
Thanks for your response!

**Comment by rootlu** [comment]
Please refer to #4
