### ISSUE TITLE
您好，可不可以发布一下豆瓣数据集，想学习一下

### ISSUE THREAD

**Issue by morningnn** [rootlu/SIAN#4]
或者发一下邮箱可以吗？1191831654@qq.com

**Comment by Kitten-Rec** [comment]
@morningnn 请问作者将豆瓣数据集发给您了么？

**Comment by rootlu** [comment]
你好，

抱歉未及时回复，豆瓣原始数据可在这里下载https://github.com/librahu/HIN-Datasets-for-Recommendation-and-Network-Embedding。

谢谢。

**Comment by rootlu** [comment]
> @morningnn 请问作者将豆瓣数据集发给您了么？



> 或者发一下邮箱可以吗？[1191831654@qq.com](mailto:1191831654@qq.com)

你好，

抱歉未及时回复，豆瓣原始数据可在这里下载https://github.com/librahu/HIN-Datasets-for-Recommendation-and-Network-Embedding 

谢谢。

**Comment by morningnn** [comment]
提供的豆瓣数据集链接打开后404了，抱歉可以重发一下吗，或按邮箱1191831654@qq.com

**Comment by morningnn** [comment]
> 没有欸

**Comment by rootlu** [comment]
> 提供的豆瓣数据集链接打开后404了，抱歉可以重发一下吗，或按邮箱[1191831654@qq.com](mailto:1191831654@qq.com)

链接可以打开，把句号去掉了。
