### ISSUE TITLE
请问yelp数据集里的act列是什么id呢？

### ISSUE THREAD

**Issue by uvj1010** [rootlu/SIAN#5]
看代码里有 user_id \t item_id \t label \t act_list 这样的注释，act_list 表示的是 user 的所有好友吗？
注意到同一个user_id，其act_list 并不等长，但同一user的多个样本中，短act_list 总是长act_list 的子集，这里是为什么吗？是因为数据集处理是根据rating时间以及建立好友时间来做的，rating之后建立的好友关系并未放入模型训练是吗？

**Comment by Kitten-Rec** [comment]
@uvj1010  请问您知道act_list代表什么了吗？

**Comment by rootlu** [comment]
你好，
抱歉未及时回复。
yelp数据集中，act_list 是user在当前item下的共同交互的好友列表，因此其长度会因item的不同而不同，具体的定义可以参考论文中的定义2。

**Comment by rootlu** [comment]
> @uvj1010 请问您知道act_list代表什么了吗？



> 看代码里有 user_id \t item_id \t label \t act_list 这样的注释，act_list 表示的是 user 的所有好友吗？
> 注意到同一个user_id，其act_list 并不等长，但同一user的多个样本中，短act_list 总是长act_list 的子集，这里是为什么吗？是因为数据集处理是根据rating时间以及建立好友时间来做的，rating之后建立的好友关系并未放入模型训练是吗？

你好，
抱歉未及时回复。
yelp数据集中，act_list 是user在当前item下的共同交互的好友列表，因此其长度会因item的不同而不同，具体的定义可以参考论文中的定义2。
